services:
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        environment:
            - API_URL=http://backend:8000
        depends_on:
            - backend
        develop:
            watch:
                - action: sync
                  path: ./frontend
                  target: /app/frontend

    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        env_file:
            - .env
        develop:
            watch:
                - action: sync
                  path: ./backend
                  target: /app/backend
                  ignore:
                      - .venv/
